[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
NODE_VERSION = "20"

# ローカル開発用の設定
[dev]
port = 8888

# Netlify Forms 設定
[forms]
  from_email = "contact@example.com"
  fields = [
    { name = "family_name", required = true },
    { name = "given_name", required = true },
    { name = "email", type = "email", required = true },
    { name = "tel" },
    { name = "zipcode" },
    { name = "address" },
    { name = "subject", required = true },
    { name = "message", required = true },
    { name = "agreement", type = "checkbox", required = true }
  ]
  spam_filter = { enabled = true, action = "block" }